### ISSUE TITLE
download_refseq: bfcadd() failed; see warnings()

### ISSUE THREAD

**Issue by esraagithub** [wejlab/MetaScope#23]
I appreciate your effort. I've recently started using metascope
when I run download_refseq function i get the following error message. I see the progress proceed but stop and gives  bfcadd() failed; see warnings()
how can i solve the problem

> sapply(all_species, download_refseq, 
+        reference = TRUE, representative = TRUE, compress = TRUE,
+        out_dir = target_ref_temp, caching = TRUE)

No ENTREZ API key provided
 Get one via taxize::use_entrez()
See https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/
No ENTREZ API key provided
 Get one via taxize::use_entrez()
See https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/
C:\Users\DELL\AppData\Local/R/cache/R/MetaScope
  does not exist, create directory? (yes/no): 
C:\Users\DELL\AppData\Local/R/cache/R/MetaScope
  does not exist, create directory? (yes/no): yes
  |====================================================================================| 100%

  |==================================================                                  |  60%bfcadd() failed; see warnings()         
  |======                                                                              |   7%bfcadd() failed; see warnings()
  |=                                                                                   |   1%bfcadd() failed; see warnings()
  |                                                                                    |   0%bfcadd() failed; see warnings()
  |                                                                                    |   0%bfcadd() failed; see warnings()
  |                                                                                    |   0%bfcadd() failed; see warnings()
  |=                                                                                   |   2%bfcadd() failed; see warnings()
  |=                                                                                   |   2%bfcadd() failed; see warnings()
  |                                                                                    |   1%bfcadd() failed; see warnings()
  |==                                                                                  |   2%bfcadd() failed; see warnings()
  |=======                                                                             |   8%bfcadd() failed; see warnings()
  |===                                                                                 |   4%bfcadd() failed; see warnings()
  |=                                                                                   |   1%bfcadd() failed; see warnings()
  |=======                                                                             |   8%bfcadd() failed; see warnings()
  |=                                                                                   |   1%bfcadd() failed; see warnings()
  |==                                                                                  |   2%bfcadd() failed; see warnings()
  |                                                                                    |   0%bfcadd() failed; see warnings()
  |======================================================                              |  64%bfcadd() failed; see warnings()
  |========                                                                                      |   9%

**Comment by aubreyodom** [comment]
Hi, can you give an example of what species are in the vector `all_species`?

**Comment by esraagithub** [comment]
all_species= c("Eukaryote", "bacteria", "Viruses")

**Comment by aubreyodom** [comment]
"Eukaryota" should be used in place of "Eukaryote"; can you see if that resolves your issue?

**Comment by esraagithub** [comment]
when i used "Eukaryote" i get this error:
 Error in value[[3L]](cond) : NCBI request not granted
Error in value[[3L]](cond) : NCBI request not granted
Error in value[[3L]](cond) : NCBI request not granted
Error in FUN(X[[i]], ...) : 
  Process halted. Your input is not a valid taxon

i see the downloading message when i write Eukaryot**a**

**Comment by aubreyodom** [comment]
Good, stick with "Eukaryota". Now can you try running with `caching = FALSE`?
