### ISSUE TITLE
metascope for assembled contig?

### ISSUE THREAD

**Issue by esraagithub** [wejlab/MetaScope#26]
hello
can i use metascope for assembled contigs?

**Comment by aubreyodom** [comment]
Hi,

If the assembled contigs are in FASTA format, then you would be able to align these if you include "-f" in the `bowtie2_options` parameter in the `align_target_bowtie()` function.

**Comment by esraagithub** [comment]
Is there similar option in subread?

في الأحد، ٤ فبراير ٢٠٢٤ ٨:٠٩ م Aubrey Odom ***@***.***> كتب:

**Comment by aubreyodom** [comment]
According to the documentation for `Rsubread::align()`:

input_format | character string specifying format of read input files. gzFASTQ by default (this also includes FASTQ, FASTA, gzipped FASTQ and gzipped FASTA formats). Other supported formats include SAM and BAM. Character values are case insensitive.

So you would use something like c("input_format" = "FASTA") or append to the MetaScope `align_details` object to pass to `MetaScope::align_target`.
