### ISSUE TITLE
logical result

### ISSUE THREAD

**Issue by esraagithub** [wejlab/MetaScope#28]
hello
i am working on a human metagenome sample.
the final csv output of metascope showed that there are some thermophilic bacteria. but it isn't logic to find thermophilic bacteria in human body. is this means metascope filled to identify the taxa correctly so i should be cautious?

**Comment by aubreyodom** [comment]
This is likely a result of ongoing contamination issues with the NCBI RefSeq library, and an issue that is not unique to MetaScope. One workaround is to filter out human reads twice by calling the filter module with two different human genomes/index sets. Another is to include alignment with the gapless human genome.

Yes, do be cautious and check your top microbes. MetaBLAST is a module with development underway that should help mitigate this issue.
